apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: "4.3.3"
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: openebs
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  values:
    engines:
      local:
        hostpath:
          enabled: true
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
    minio:
      enabled: false
    csi:
      enabled: false
    loki:
      enabled: false
    lokiCanary:
      enabled: false
    alloy:
      enabled: false
    mayastor:
      enabled: false
      csi:
        enabled: false
      etcd:
        enabled: false
      loki:
        enabled: false
      alloy:
        enabled: false
