apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs-localpv
      version: "4.3.3"
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: openebs
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  values:
    engines:
      local:
        hostpath:
          enabled: true
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastore:
          enabled: false
    minio:
      enabled: false
    localpv-provisioner:
      basePath: "/var/mnt/local-volume"
      reclaimPolicy: Retain
