apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: metallb
resources:
  - namespace.yaml
  - release.yaml
  - repository.yaml
  - ip-address-pool.yaml
  - l2-advertisement.yaml
