apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-controller 
  namespace: flux-system
spec:
  interval: 1m
  timeout: 5m
  retryInterval: 1m
  path: ./infrastructure/controllers/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
