apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  proxmox.yaml: |
    - Proxmox:
        href: https://proxmox.justinshomelab.dev:8006
        description: Proxmox Cluster
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/jmerhib/pi-cluster
  services.yaml: |
    - Services:
      - Pi-hole:
          icon: pi-hole
          href: http://192.168.2.29:8080/admin
          description: DNS sinkhole
          widget:
            type: pihole
            url: http://192.168.2.29:8080
            version: 6
            key: "VuzYq33jbEo2aZztPItkMmtusArfUquGeuhuFLTER+Q="
            fields: ["queries", "blocked", "blocked_percent", "gravity"]

    - Monitoring:
      - Grafana:
         icon: grafana
         href: https://grafana.justinshomelab.dev/
         description: Grafana Monitoring

    - Personal:
      - Audiobookshelf:
         icon: audiobookshelf
         href: https://audio.justinshomelab.dev
         description: Audiobooks/Podcasts
         widget:
           type: audiobookshelf
           url: https://audio.justinshomelab.dev
           key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXlJZCI6ImUwMzZiODc4LWJlNjQtNGExMS04ZjJmLTc2MzcwOGZiNDYyNSIsIm5hbWUiOiJndWVzdCIsInR5cGUiOiJhcGkiLCJpYXQiOjE3NTk4Njg4NTF9.9adjma5-qV6-IRNBNWmgigctc7QxJbul0F2oA_Gvtos

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
