apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  proxmox.yaml: |
    - Proxmox:
        href: https://proxmox.justinshomelab.dev:8006
        description: Proxmox Cluster
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/jmerhib/pi-cluster
  services.yaml: |
    -Services:
      - Pi-hole:
        icon: pi-hole
        href: http://192.168.2.28:8080/admin
        widget:
          type: pihole
          url: http://192.168.2.28:8080
          version: 6
          key: "0pP3CAJZKtAU0mTFYOSiKTLLul3jhXVEaPLfCTiOfhQ="
          fields: ["queries", "blocked", "blocked_percent", "gravity"]
    - My First Group:
      - Grafana:
            href: http://grafana.justinshomelab.dev/
            description: Grafana Monitoring

    - My Second Group:
      - Audiobookshelf:
            href: http://audio.justinshomelab.dev/
            description: Audiobook/Podcasts

    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
