apiVersion: v1
kind: PersistentVolume
metadata:
  name: homepage-pv
  labels:
    app: homepage
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /data/homepage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node01
                - node02
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      app: "homepage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      app: "homepage"
