apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv
  labels:
    app: pihole
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /data/pihole
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node01
                - node02
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
  selector:
    matchLabels:
      app: "pihole"
