---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      app: "pihole"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dns-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      app: "pihole"
