---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data-pvc
  namespace: linkding
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: linkding-data-pvc
  resources:
    requests:
      storage: 1Gi
