apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data-pvc
  namespace: linkding 
spec:
  storageClassName: "" 
  accessModes:
    - ReadWriteOnce
  volumeName: linkding-data-pvc
  resources:
    requests:
      storage: 1Gi
